language: csharp
mono: none
dotnet: 6.0 

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test Tests/ebay-oauth-csharp-client-tests.csproj

after_script:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
